### ISSUE TITLE
Pouvoir sélectionner plusieurs secteurs d'activité

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#10]
Une marque peut appartenir à plusieurs secteurs d'activité comme dans l'ancien site.

**Comment by jabberwooki** [comment]
C'est une nouveauté par rapport à ce qui a été validé. Classé en demande d'amélioration.

**Comment by SandMat** [comment]
Pas vraiment nouveauté puisque c'était déjà le cas dans l'ancien site.

**Comment by jabberwooki** [comment]
Corrigé.
Cardinalité du champ "Secteur d'activité" passé de 1 à illimité.
Widget du champ passé de liste à boutons radio pour faciliter la saisie à l'utilisateur.
