### ISSUE TITLE
V3 S4-1 Finaliser calendrier structure

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#101]
[Carte Trello](https://trello.com/c/KGlzvlVu/347-4-1-finaliser-calendrier-structure)

Transformer en bouton le lien [Ajouter un événement](http://crealead.korora.fr/espace-co-entrepreneur/informations) qui se trouve sous le titre Calendrier Structure.

En profiter pour faire la même chose avec le lien [Ajouter une réservation](http://crealead.korora.fr/espace-co-entrepreneur/agenda-salles) dans l'agenda des salles (je l'indique ici parce qu'il n'y a rien à ce sujet dans la carte trello des Salles).

**Comment by yvandouenel** [comment]
C'est fait, j'ai juste ajouté la class "red-button-link" à ces deux boutons
