### ISSUE TITLE
Un compte annulé ne supprime pas l'entrée du trombi

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#102]
Supprimer un utilisateur présent dans le trombi, en le gardant mais en désactivant et dépubliant son contenu. 
Il reste présent dans le trombinoscope. La fiche n'est pas ouvrable par un coE.

**Comment by jabberwooki** [comment]
Corrigé.
Le filtre "Statut de publication=publié" existait mais était insuffisant.
L'ajout du filtre "Utilisateur=actif" permet de ne plus lister les utilisateurs désactivés (bloqués).
Hotfix déployé en prod.
