### ISSUE TITLE
offres en accès libre

### ISSUE THREAD

**Issue by yvandouenel** [jabberwooki/crealead#113]
les offres sont en accès libre : http://www.crealead.com/offres/vae-pour-le-titre-professionnel-formateur-professionnel-dadultes et sont donc référencées sur google...

**Comment by jabberwooki** [comment]
Je note que les demandes sont aussi en accès libre. Mais pas tant que ça.
Pour pouvoir accéder à la page détaillée d'une offre ou d'une demande, il faut passer par la liste Offres ou la liste Demandes. Ces listes ne sont pas accessibles aux anonymes donc Google ne peut pas les voir.
La seule faille, c'est si un coe publie une actu (publique) dans laquelle il a la mauvaise idée de mettre un lien vers une offre ou une demande, alors à ce moment-là, les moteurs de recherche verront la page détaillée.
Donc, j'ai ajouté du code dans les deux fichiers .module concernés pour retourner "ACCÈS REFUSÉ" si un visiteur anonyme suit un tel lien. J'ai fait cette modif dans un hotfix que j'ai déployé en prod.
