### ISSUE TITLE
V3 S5-6 Recommandations : liste formations

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#118]
Intégration des 2 nouveaux champs "Recommandé par x personnes" et "Je recommande..." dans la vue Formations, mais aussi dans l'onglet "Solutions" d'une page de marque.

J'ai voulu faire du positionnement absolu pour aller vite. Ca a bien marché chez moi mais ça a fait péter la bordure ombrée des items Formation sur la recette. Donc j'ai commenté le code css. Ca se trouve dans fichier repository/modules/features/crealead_trainings/css/crealead_trainings.css

Pour retrouver la formation Impression 3D, qui contient ces deux champs, il suffit d'utiliser le filtre de recherche Formations avec "TecRD" comme nom de marque.

**Comment by yvandouenel** [comment]
Je n'arrive pas à trouver comment mettre en place ce mécanisme en local. Du coup je ne peux pas intégrer.

**Comment by yvandouenel** [comment]
Ok, c'est corrigé
