### ISSUE TITLE
Fonte très pixellisée

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#12]
La police utilisée pour le site est très pixellisée sur la plupart des navigateurs (sauf Edge). Or certains entrepreneurs (mauvaise vue ou dyslexiques) n'arrivent pas à la lire. 
Mettre une police plus standard.

**Comment by SandMat** [comment]
Mettre une police plus standard à tous les endroits où ce n'est pas indispensable (Ex : Voir toutes les actualités).

**Comment by yvandouenel** [comment]
Fait sur la page d'accueil (Voir toutes les actualités) mais il serait très intéressant de vérifier auprès de la personne que cela gêne vraiment quels sont les autres textes à modifier.
