### ISSUE TITLE
Fiches entrepreneur et marque : cacher ce qui ne sert à rien

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#13]
A cacher 
- les groupes métier (usage futur en Intranet) : à cacher au moins dans la fiche publique
- les thématiques : à cacher dans le backoffice de la fiche tant que les pages d'atterrissage ne sont pas mises en place
- le statut salarié ou CAPE : ne pas l'afficher dans la vignette de la marque, mais garder l'entrée dans le backoffice entrepreneur. Afficher "Titulaire d'un CAPE" ou "Salarié" tout en bas de la fiche entrepreneur ouverte.

**Comment by jabberwooki** [comment]
Champ Groupe Métier retiré de l'affichage Complet (via Display Suite).
Champ Pages thématiques (via le hook crealead_brands_form_brand_node_form_alter()).
Champ Statut retiré de l'onglet Entrepreneurs et ajouté en bas de la page profil. La valeur "Contrat CAPE" est remplacée par "Titulaire d'un CAPE".

**Comment by SandMat** [comment]
Je ne trouve pas la mention "Titulaire d'un CAPE"

**Comment by jabberwooki** [comment]
Champ Statut replacé en bas de la fiche entrepreneur.
