### ISSUE TITLE
Request Time-Out à la création

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#14]
Supprimer les Request Time-Out dès qu'on crée un élément

**Comment by jabberwooki** [comment]
C'est quoi créer un élément ?
Est-ce que ce time-out se produit pour la création d'un utilisateur, d'une marque, d'un client, d'une référence, d'une réunion d'info ?

Yvan, est-ce que le paramètre PHP max_execution_time n'est pas réglé trop bas sur ton serveur ?

**Comment by SandMat** [comment]
A priori tout ça. Je réessaierai ce WE, parce que j'ai tellement pris l'habitude de ce message que je ne le remarque même plus! :)
