### ISSUE TITLE
Supprimer le "Gérer l'affichage" pour le compte utilisateur et les marques

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#16]

**Comment by jabberwooki** [comment]
Cet onglet apparait dès qu'un utilisateur possède la permission "Administrer les utilisateurs". C'est un comportement du noyau Drupal. Sur le site Crealead, seuls les rôles administrateur et webmaster voient cet onglet.
Il existe une solution pour supprimer cet onglet, en ajoutant un petit bout de code custom ou en appliquant un patch comme décrit dans cette [issue](https://www.drupal.org/node/1837156) du module Field UI.

On laisse ainsi ou bien j'applique ce correctif ?

**Comment by SandMat** [comment]
Non OK, c'est bon comme ça. Je croyais l'avoir vu pour un entrepreneur lambda.
