### ISSUE TITLE
Remettre le formulaire de contact dans la fiche marque

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#17]

**Comment by jabberwooki** [comment]
Le formulaire de contact s'affiche seulement si le champ email est renseigné.
Ce champ a été déplacé au niveau du code pour des raisons d'intégration graphique donc le test contrôlant si le champ email est renseigné était devenu sans effet.
Modification du test pour aller chercher le champ directement dans l'objet marque au lieu de vérifier sa présence dans l'interface.
Le mécanisme fonctionne à nouveau. La visibilité du formulaire de contact et de la liste des contacts pris se fait de la manière suivante :
![visibilite-formulaire-contact-marques](https://cloud.githubusercontent.com/assets/1741337/11836013/05c48052-a3d8-11e5-9ce8-8910f1c13dcd.png)

A NOTER
A tout moment, un propriétaire de marque peut désactiver l'affichage du formulaire de contact s'il ne souhaite plus recevoir de contacts via le site Crealead. Pour cela, il faut descendre tout en bas du formulaire de modification de la marque et cliquer sur l'onglet vertical "Champs Crealead" puis dans le menu déroulant "Formulaire de contact" choisir "Aucun(e)".
