### ISSUE TITLE
Entrepreneur par défaut

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#18]
Quand un référent crée un nouvel utilisateur, il faut qu'il soit entrepreneur par défaut (aujourd'hui, pas de rôle pour le nouvel utilisateur)

**Comment by jabberwooki** [comment]
C'est codé.
Si l'utilisateur en train de créer un nouvel utilisateur a le rôle référent, alors par défault la case du rôle entrepreneur est cochée dans le formulaire de création de l'utilisateur.

**Comment by SandMat** [comment]
Le pb, c'est que les référents n'ont pas le formulaire pour cocher les rôles. C'est bien pour ça que je voulais que ce soit un rôle par défaut. Sinon je leur aurais demandé de cocher le rôle!!!!
Tester avec Elisabeth ou Farba, ça ne marche pas!

**Comment by jabberwooki** [comment]
Corrigé et testé en local avec un référent qui n'a que le rôle référent. Dans le formulaire de création d'un utilisateur, le référent a maintenant le choix suivant : 

![creation-utilisateur-choix-du-role](https://cloud.githubusercontent.com/assets/1741337/13329539/b2803058-dbf4-11e5-9521-eeea1a197c73.png)

[ Info dev ]
Réalisé avec ajout du module Role Assign.

**Comment by SandMat** [comment]
Le bloc ci-dessus (Assignable roles) apparait aussi dans l'onglet "Profil entrepreneur" quand on est connecté en tant que référent simple (ex : Elisabeth). Doublon?
Ou fait exprès?
Canditat --> Candidat

**Comment by jabberwooki** [comment]
Bloc supprimé de l'affichage.

_[Info dev]
Impossible de trouver pourquoi ce bloc est affiché dans ce formulaire. Aucune info trouvée dans les forums ni dans les issues des modules concernés Profile2 et Roleassign.
Donc codage d'une fonction custom crealead_profiles_after_build() dans le fichier crealead_profiles.module._
