### ISSUE TITLE
Recherche marques : auto-complétion champ marque inactive

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#23]
Il faut réactiver le mécanisme de complétion.

**Comment by jabberwooki** [comment]
Le mécanisme d'auto-complétion est buggé et complexe à corriger (voir les issues du module views_autocomplete_filter sur drupal.org).

Solution adoptée momentannément : suppression de l'auto-complétion.
La recherche par nom de marque fonctionne quand meme. Par exemple, une recherche sur "cal" retourne : 
- Calluna Communication
- Delphine Lescallier

**Comment by SandMat** [comment]
Pas chez moi! Ça me renvoie des textes tapés dans mon navigateur.
