### ISSUE TITLE
Ajout d'un rôle à un utilisateur : comment faire

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#25]
Comment faire pour ajouter un rôle à un utilisateur (rajout d'entrepreneur à un référent)?  
18/11 : Seul l'admin y a accès dans la pratique mais ce n'est pas normal.

**Comment by SandMat** [comment]
En fait, lié à la demande d'amélioration #18. C'est elle qu iest importante.

**Comment by jabberwooki** [comment]
Actuellement les rôles disponibles sont : administrateur, webmaster, référent, pôle gestion, entrepreneur, candidat et rédacteur.
Le rôle rédacteur n'est pas du tout utilisé.
Le rôle candidat n'est pas encore utilisé.

J'ai installé le module contrib **roleassign** qui fournit la nouvelle permission _Attribuer des rôles_.
Je l'ai paramétré de la façon suivante.
- Les rôles pouvant être attribués sont : candidat, entrepreneur et pôle gestion.
- Les rôles pouvant attribuer ces rôles sont : pôle gestion, référent, webmaster et administrateur.
