### ISSUE TITLE
Rendre possible l'ajout de non entrepreneurs à une marque

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#26]
Pourquoi O Raynal n'apparait pas comme entrepreneur possible en création de marque (Stratèje créée, en tant que SMA, et le nom n'apparait pas dans la liste des entrepreneurs possibles). Il faut que quiconque est utilisateur du site puisse être référencé dans une marque.

**Comment by jabberwooki** [comment]
Actuellement, la liste des personnes disponibles pour l'ajout à une marque est celle des utilisateurs ayant au moins le rôle entrepreneur. Si l'on supprime cette limitation, il y a 2 conséquences :
- Tout utilisateur enregistré dans Drupal pourrait être rajouté à une marque, y compris les personnes du pôle gestion et plus tard, les personnes ayant le rôle (à venir) de candidat.
- Une personne non entrepreneur sera alors visible dans l'onglet Entrepreneurs de la fiche marque. Mais un clic sur son nom, ou sa photo, conduira à une page blanche puisqu'il n'aura pas de profil entrepreneur.

Est-ce bien ça qui est demandé ?

**Comment by SandMat** [comment]
Non, ce qui était demandé, c'est qu'un référent, par exemple, puisse être mis dans une marque. 
Mais ce besoin est un faux besoin, puisqu'à partir du moment où il appartient à une marque, il est entrepreneur... et on lui donnera donc aussi ce statut. 
Bref, laisse tomber.
