### ISSUE TITLE
Bug d'insertion d'image dans une actu

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#27]
Créer une actu, modifier la date, cliquer dans le corps de l'actu et insérer une image de scald. L'image s'insère dans la date.

**Comment by jabberwooki** [comment]
Deux remarques :
- Sur mon poste de travail Linux Ubuntu 12.04, il n'est pas possible de faire un glisser/déposer d'une image Scald dans le corps d'une actu avec le navigateur Chrome. Par contre, la manip se fait très bien avec Firefox. Pouvez-vous me dire si vous rencontrez le même problème ou pas ? Notez chaque fois : Nom de l'OS (windows, mac, linux) - Version de l'OS - Nom du navigateur - Version du navigateur.
- Lorsque le glisser/déposer fonctionne (Firefox dans mon cas), le bug n'est pas reproductible.

**Comment by SandMat** [comment]
Je réessaierai plus tard. Pas urgent, les entrepreneurs ne sont pas concernés.
