### ISSUE TITLE
Création de marque : pb de logo

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#28]
Sans choix de loge, une photo s'affiche quand même (la dernière utilisée?)

**Comment by SandMat** [comment]
S'il faut une photo par défaut, mettre une silhouette humaine

**Comment by SandMat** [comment]
Ah non, pardon, la silhouette c'est pour la fiche entrepreneur. Même pb, d'ailleurs. 
Pour la marque, un carré blanc?

**Comment by jabberwooki** [comment]
Le paramétrage de l'image logo par défaut n'était pas fait.
Le logo par défaut est maintenant celui-ci :
![default_logo](https://cloud.githubusercontent.com/assets/1741337/11893108/1f20350e-a56e-11e5-9c04-861a7bc8f0f5.png)
