### ISSUE TITLE
Une marque doit être modifiable par tous les utilisateurs rattachés à cette marque

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#30]
un entrepreneur qui n'a pas créé de marque mais qui appartient à une marque doit pouvoir créer des articles et actus pour cette marque! Sinon, il passe où l'article?

**Comment by SandMat** [comment]
Plus tard. Pour l'instant ils acceptent l'idée qu'il y a un propriétaire de la marque.
