### ISSUE TITLE
Affichage actus et articles en deux colonnes dans onglet blog

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#32]
Dans le blog, la disposition des actus (avec photos) et article de fond (sans photo) choque. On avait prévu 2 colonnes (Cf US).
2/3 pour les actus, 1/3 pour les articles. La photo ne s'affiche pas dans les vignettes Articles, s'il y en a une. 
Toutes les actus de la marque sont affichées, 20 par page

**Comment by SandMat** [comment]
Même si on ne fait pas ce développement tout de suite, serait-il possible d'aligner à gauche les articles et actus? Aujourd'hui, les photos sont à gauche, les textes sont centrés. Ca fait bizarre. 
Et encadrer chaque article/actu de façon à mieux les séparer?

**Comment by yvandouenel** [comment]
Les actualités prennent donc 2/3 de l'écran et les articles le tiers restant. J'ai ajouté des titres de rubrique et l'affichage d'une image (si elle existe) sur les articles . Voir l'exemple en preprod : http://crealead.korora.fr/annuaire-entrepreneurs/wembla-conseil
