### ISSUE TITLE
Titre d'une réunion d'information

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#33]
Création de réunion d'information : pourquoi un titre obligatoire? Possibilité de mettre "Réunion d'information - date" par défaut? Idem pour les heures. Seule la date change.

**Comment by jabberwooki** [comment]
Dans Drupal, pour tout type de contenu, le champ titre est obligatoire et fait partie du fonctionnement du noyau drupal. Sans titre obligatoire, comment faire la différence entre les contenus publiés dans la liste de tous les contenus : http://www.crealead.com/admin/content

Ensuite, concernant les réunions d'information seules, on ne peut pas se contenter du titre unique "Réunion d'information" (pour la même raison que ci-dessus). Il faut en effet un titre au format suivant :
**Réunion d'information du (jour) (mois)**
Pour cela, il faut un développement spécifique qui ferait les choses suivantes :
- A la création d'une nouvelle réunion, le champ titre contient automatiquement la phrase "Réunion d'information du".
- A la validation du formulaire de création de la réunion, interception des infos avant sauvegarde en base de données, récupération de la valeur de la date de réunion, rajout de l'info "jour mois" à la suite du titre.

Estimation du temps de réalisation (codage + tests + packaging + déploiement) : 2 à 3 heures.
Est-ce que je fais ?

**Comment by SandMat** [comment]
On ne fait pas pour l'instant. J'ai montré à Cathy comment faire et elle a pris le pli.
