### ISSUE TITLE
Pb de création simultanée fiche marque + réalisation

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#34]
Perturbant : quand on crée une réalisation, il faut l'enregistrer... puis penser à enregistrer aussi la fiche marque. 18/11 : en fait la réalisation est bien créée, et peut être utilisé plus tard dans la fiche marque. Sauf que si on ne le sait pas, on recrée la réalisation... et on se retrouve avec plusieurs fois la réalisation. --> message pour avertir de penser à sauvegarder la fiche marque

**Comment by jabberwooki** [comment]
Le fait de pouvoir créer une réalisation en même temps qu'une fiche marque est une facilité non prévue au départ que j'ai mis en place pour une meilleure expérience utilisateur. Mais en effet, ce dernier peut oublier facilement de sauvegarder sa fiche marque. Donc deux possibilités :
1. Supprimer cette facilité. Le scénario sera alors le suivant pour un utilisateur : 
- Création de la fiche marque si elle n'existe pas encore, sinon modification, puis enregistrement. 
- Création d'une réalisation, puis sauvegarde.
- Retour à la fiche marque en modification pour lier la réalisation à la marque.
1. Mettre un message d'avertissement. Mais c'est bien connu, les développent préparent de beaux messages qui expliquent bien ce qu'il faut faire ou ne pas faire, les utilisateurs ne lisent pas les beaux messages parce que ça les gavent, et le problème se produit malgré tout.

Quelle solution mettre en place ?

PS : il n'est pas envisageable de dire qu'il suffit d'enregistrer automatiquement la fiche marque lorsque l'utilisateur enregistre sa réalisation, pour au moins 2 raisons :
- S'il lui prend l'idée de saisir une réalisation avant d'avoir rempli tous les champs obligatoires de la fiche marque, la sauvegarde de la fiche marque sera refusée, mais la réalisation, elle, sera enregistrée. Et à tous les coups, l'utilisateur reprendra la saisie de sa fiche mais recréera la même réalisation. En bref, en voulant corriger un éventuel problème (réalisations créées en doublon), on le crée d'une autre manière.
- S'il a saisi (même sans s'en rendre compte) tous les champs obligatoires alors sa marque et sa réalisation seront correctement sauvegardées et liées l'une à l'autre, mais l'utilisateur ne comprendra pas pourquoi il est sorti du formulaire de saisie de sa fiche alors qu'il n'a pas terminé.

**Comment by SandMat** [comment]
Pour l'instant on laisse comme ça. On verra les retours.
