### ISSUE TITLE
Notification au référent non reçu

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#37]
Quand un entrepreneur sauvegarde sa fiche (entrepreneur ou marque) avec notification au référent, le référent ne reçoit pas la notification. Est-ce dû à notre anti-spam?

**Comment by jabberwooki** [comment]
Testé sur instance de dev locale et sur serveur de recette. Les deux types de demande parviennent bien au référent de l'entrepreneur.
Il faut vérifier : 
- que les emails de notification n'atterrissent pas dans le dossier de spam de ta messagerie.
- qu'ils ne soient pas classés en milieu de liste des messages et non en tête, même s'ils viennent d'être envoyés (c'est le cas chez moi).
