### ISSUE TITLE
Dépublication des marques

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#39]
En tant qu'entrepreneur, créer une marque. 
La faire valider par le référent, qui la publie. La marqu apparait bien sur le site. 
Ensuite, si l'entrepreneur modifie sa fiche marque, la marque est dépubliée. 

Dans les champs spéciaux en bas à gauche, il y a d'ailleur un message, au moment de la moification de la fiche, du style "vous ne pouvez pas publier cette fiche, soit celle-ci, soit votre fiche entrepreneur n'a pas été validée par votre référent". Or la fiche marque a été validée et la fiche entrepreneur aussi.

**Comment by jabberwooki** [comment]
Cause réelle du problème : les référents (et webmaster, et pole gestion) pouvaient publier une marque sans l'avoir validée au préalable. Le controle "est-ce que le profil coe est validée + est-ce que la marque est validée" n'était appliqué qu'aux coes. Il l'est maintenant à tous les roles.
