### ISSUE TITLE
Accueil - Menu pied de page

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#4]

**Comment by jabberwooki** [comment]
Menu pied de page déjà présent dans la feature kcore.
Install et activation du module site_map.
Ajout d'un lien de menu "Plan du site" dans le menu pied de page.

Il reste à intégrer graphiquement les liens de ce menu.

**Infos développeur, pour mettre à jour les différentes instances.**
1- Mise à jour du dépot local
_git pull_

2- Puis deux possibilités :
_./scripts/build.sh_
_cd www_

ou bien
_cd www_
_drush dl site_map -y_

3- Terminer par :
_drush updb_
_drush fra -y_
_drush cc all_

**Comment by yvandouenel** [comment]
Entendu, c'est fait mais cela demandait aussi de donner les droits de visualisation du module site_map pour les internautes non-identifiés. Je l'ai fait sur le serveur mais pas intégré dans une feature
