### ISSUE TITLE
Pas de plan d'accès pour les réunions d'info

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#41]
Aller sur "S'inscrire à une réunion d'information", ouvrir une réunion. 
Cliquer sur "Version Imprimable", produire le PDF. 
Le plan d'accès n'apparait pas sur le PDF.

Pb annexe: la photo utilisée pour la street view comporte l'ancien logo. Voir avec nous comment avoir une photo plus à jour.

**Comment by jabberwooki** [comment]
Plan et photo sont maintenant visibles.
En cliquant sur Imprimer, on obtient la version simplifiée de la page dans un nouvel onglet. Il faut utiliser la fonction imprimer de son navigateur pour pouvoir imprimer la page.

[ Info dev ]
Obtenu en décochant "Send to printer" dans les paramétrages du module print.
