### ISSUE TITLE
Les formats de Titres prédéfinis ne marchent pas

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#43]
Que ce soit dans la fiche Entrepreneur ou dans la fiche Marque, dans un champ texte riche (Description, Biographie...), taper une phrase. Lui attribuer un style pré-défini (Ex : Titre 1), enregistrer. 
Le format Titre 1 n'est pas pris en compte. 

Les tabulations et les tableaux ne sont pas non plus pris en compte.

**Comment by jabberwooki** [comment]
Origine du problème : tous les champs de type Texte long, dans un profil entrepreneur ou dans une marque étaient paramétrés pour n'accepter que les formats Filtered HTML et Plain text.
Corrigé en ajoutant le format Full HTML.
