### ISSUE TITLE
Mettre une aide pour les compétences

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#44]
Pour les compétences, mettre une ou 2 lignes expliquant 
- que ce sont des mots-clefs 
- qu'elles sont limitées à 5
- qu'il faut les séparer par des virgules
- qu'elles sont en auto-complétion (vérifiez bien qu'elle n'existe pas déjà dans la liste avant de la ressaisir)

**Comment by jabberwooki** [comment]
Texte d'aide ajouté.

**Comment by SandMat** [comment]
OK sur la fiche marque. 
A mettre aussi pour la fiche entrepreneur
