### ISSUE TITLE
Réunion infos affichées dans l'ordre chronologique

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#46]
Aller sur Contenu/Inscriptions aux réunions d'infos. 
Les réunions s'affichent dans l'ordre chronologique, ce qui fait qu'il est très difficile de trouver les réunions actives, maintenant que nous en avons plein. 
Merci de les afficher dans l'ordre inverse.

**Comment by jabberwooki** [comment]
Modif effectuée.
(via paramétrage du format Tableau dans la vue correspondante)
