### ISSUE TITLE
Pb avec certains logos

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#47]
Certains logos de marques débordent sur les informations générales sur Firefox.
Redimensionner automatiquement le logo ou refuser les trop gros logos.

**Comment by jabberwooki** [comment]
Mise en place du module contrib imagecache_canvasactions pour traiter les images les logos de façon conditionnelle (test si format portrait ou paysage).

**Comment by SandMat** [comment]
J'ai essayé avec un logo horizontal de Wembla, et il déborde. 
Cf marque "Ma 2ème marque test" créée sous le user Paul Boucher.

**Comment by yvandouenel** [comment]
donner comme règle css : img{max-width:255px;}

**Comment by yvandouenel** [comment]
Fait
