### ISSUE TITLE
Rendre la fiche marque plus accessible quand elle n'est pas publiée

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#50]
Trouver un moyen intelligent de rendre la fiche marque plus facilement trouvable par l’entrepreneur qui l'a créée tant qu'elle n'est pas publiée. 
Un menu Mes marques quand on clique sur son propre nom en haut à droite? Ou la marque qui s'affiche dans la fiche entrepreneur même si elle n'est pas publiée, cliquable uniquement par l’entrepreneur et les admin?

**Comment by SandMat** [comment]
Solution choisie : 
Créer une vue : Voir mes contenus, en sous-menu de Contenu.
Cette vue affiche tous les contenus de l'utilisateur.

**Comment by jabberwooki** [comment]
Nouvelle vue "Voir mes contenus" créée.
Accessible dans le menu d'administration à Contenu > Voir mes contenus.
