### ISSUE TITLE
Mail du formulaire de contact

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#52]
- l'expéditeur du mail du formulaire de contact est Christophe Espiau! Mettre soit un mail neutre style contact@crealead.com, soit le mail de la personne qui a rempli le formulaire de contact. 
- il n'y a pas de message, à part le message qu'a écrit la personne dans le formulaire. On pourrait mettre une intro du style : "la personne <adresse mail> a rempli votre formulaire de contact sur le site Crealead. 
  Elle souhaite vous poser une question/prendre contact avec vous. 
  Son message :"

Aujourd'hui, j'ai obtenu ça :
Test
sandrine.mathon@wanadoo.fr

TEst

**Comment by jabberwooki** [comment]
- Adresse email du site christophe.espiau@gmail.com changée en contact@crealead.com.
- Message d'intro créé pour le message email de notification.

[Info dev]
Message créé en modifiant la règle Email de contact vers une marque dans Rules.

**Comment by SandMat** [comment]
Testé le 01/03. Mail jamais reçu.

**Comment by jabberwooki** [comment]
Testé le 02/03. Mail bien reçu.
Sur la  plate-forme de recette, faire attention à l'adresse paramétrée pour le [reroutage](http://crealead.korora.fr/admin/config/development/reroute_email) des mails pendant les tests.

**Comment by SandMat** [comment]
02 mars : OK pour le texte du mail. Vérifier pourquoi je ne reçois rien.
