### ISSUE TITLE
Mettre secteur d'activités à la place du bloc Groupe Métier

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#55]
Dans la fiche Marque, le groupe Métier ne doit plus s'afficher. 
Mettre à la place les secteurs d'activités, avec le même principe que les groupes métier: cliquable pour lister toutes les marques de ce secteur.

**Comment by yvandouenel** [comment]
Sommes nous bien sûr de vouloir changer de place le secteur d'activité ? 
Après réflexion, il me semble que cela va déséquilibrer la zone d'entête des marques. J'attends votre réaction pour changer cela...

**Comment by SandMat** [comment]
En fait, on avait dit qu'on grossissait l'accroche. Mais je ne me rends pas bien compte. Il faudrait que je voie ce que ça donne.

**Comment by SandMat** [comment]
Ce qu'il y a de sûr, c'est qu'il faut aligner la description et les solutions à droite, comme si le bloc Mots-clefs était tout le temps là et prenait toute la hauteur.

**Comment by yvandouenel** [comment]
Col 9 à gauche et col 3 et droite

**Comment by jabberwooki** [comment]
Séparation du contenu de l'onglet Infos générales en deux colonnes 9 -3 réalisé.
