### ISSUE TITLE
Actus entrepreneurs à afficher en ordre chronologique inverse

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#56]
Actus entrepreneurs à afficher en ordre chronologique inverse

**Comment by jabberwooki** [comment]
C'est déjà le cas.
Le seul champ Date actuellement disponible pour ce type de contenu est le champ "created" (champ système Drupal) qui enregistre automatiquement la date de création d'un article.
Les actus d'un entrepreneurs sont listées en ordre chronologique inverse par rapport à ce champ.

**Comment by SandMat** [comment]
29/03 : il n'y a pas de tri sur les actus marque. 
Utiliser systématiquement la date où l'actu est écrite/modifiée (pas d'utilisation de la date d'événement).

**Comment by jabberwooki** [comment]
Corrigé. Le comportement est le suivant.

Une actu comporte un champ technique Date de tri, non visible. Le tri se fait sur ce champ, de manière descendante.
Lors de l'enregistrement d'une actu (création ou modification), si aucune valeur n'est saisie dans le champ Date de l'évenément, alors la date de création (date système) est copiée dans le champ Date de tri, sinon c'est la date de l'événement qui est copiée.
