### ISSUE TITLE
Actus qui disparaissent du mini-site marque

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#60]
Se connecter en tant que référent. 
Aller sur Modifier une actu d'un mini-site marque. Enregistrer (même sans modifier de champ). 
--> la fiche n'apparaît plus sur le mini-site marque.

Pourtant elle est toujours marquée comme publiée. 

J'imagine que c’est le même pb qui fait qu'on ne peut pas publier une actu marque au niveau de Crealead, sans qu'elle disparaisse du mini-site marque. Toutefois là, il n'y a pas de raison qu'elle disparaisse. Et surtout où est-elle "publiée"?!

**Comment by jabberwooki** [comment]
CORRIGÉ.
Lorsqu'un utilisateur connecté crée une actu, il peut la rattacher à une ou plusieurs de ses marques.
Désormais, lorsqu'un autre utilsateur modifie cette actu, il obtient la liste des marques de l'auteur de l'actu, au lieu de la liste de ses propres marques, ou pas de liste du tout si celui-ci n'est rattaché à aucune marque (par ex. Elisabeth C).
