### ISSUE TITLE
Site mobile : les marques sont en vrac

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#61]
Aller sur crealead.com à partir d'un portable. 
Aller sur Chercher un prestataire.
Les marques s'affichent en vrac. 

--> mieux séparer les marques (encadrement?)
--> les aligner correctement

**Comment by yvandouenel** [comment]
J'ai pas mal amélioré la mise en page sur smartphone en général. J'ai mieux mieux séparé les marques mais je n'ai pas vu de pb d'alignement (les marques sont les unes sous les autres).
