### ISSUE TITLE
Références client : vignette blanche si pas de logo

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#64]
quand un coE met une référence client sans logo, le nom du client apparaît sur la première ligne. Quand il y a une vignette référence complète à côté, c'est complètement décalé. 
Mettre une vignette vide à la place du logo?

**Comment by jabberwooki** [comment]
Pour le logo, l'image par défaut suivante a été paramétrée : 

![default-logo](https://cloud.githubusercontent.com/assets/1741337/14649096/d7d7fa7a-0665-11e6-8dd5-e5a26e2c4d6b.jpg)

**Comment by SandMat** [comment]
Le logo par défaut n'y est plus sur la production (27/05)

**Comment by SandMat** [comment]
Allo?

**Comment by jabberwooki** [comment]
J'ai mis en place le loge par défaut sur la prod.
Deux remarques :
