### ISSUE TITLE
Meta balise title ne fonctionne pas 

### ISSUE THREAD

**Issue by yvandouenel** [jabberwooki/crealead#66]
Ex : http://www.crealead.com/devenez-co-entrepreneur/entrepreneur-ou-artisan-en-activite-pourquoi-nous-rejoindre : Balise meta > title a été modifiée sans résultat sur la balise title

**Comment by jabberwooki** [comment]
Corrigé.

[Info dev] Problème difficile à régler. Il s'agissait d'un conflit entre les modules Metatags et Page Title.
Résolu en implémentant le hook_preprocess_html() dans la feature kseo.module (voir commentaires dans ce fichier) et en customisant le fichier template html.tpl.php.
