### ISSUE TITLE
Disparition du mail quand modif candidat

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#67]
Aller sur une réunion d'information/Gérer les inscriptions. 
Modifier un candidat.
Le champ "adresse mail" n'est plus dans le formulaire.

**Comment by jabberwooki** [comment]
Corrigé en attribuant la permission "Inscrire d'autres personnes" au rôle Administrateur. Cette permission était déjà attribuée au rôle Pôle gestion.

**Comment by SandMat** [comment]
Le champ mail apparaît bien quand on modifie l'inscrîption... mais si on le modifie, la modification n'est pas conservée.

**Comment by jabberwooki** [comment]
Non reproductible.
Création d'un compte admin de test (email=atest@korora.fr, pass=atest.0) et connexion sous ce compte. Il est possible de modifier l'email de l'inscription Volfoni Test (email passé de sandrine@test.com à sandmat@test.com).

**Comment by SandMat** [comment]
My fault, j'ai gardé la formulation générique de Cathy : en fait le problème se produit quand il n'y a rien dans le champ e-mail, et que l'administrateur modifie la fiche pour rajouter l'adresse mail. Alors elle n'est pas prise en compte.

**Comment by jabberwooki** [comment]
Re-testé et toujours non reproductible.
En étant connecté en admin de test, j'ai pu enregistrer une adresse email pour le candidat Test TEst, qui n'en n'avait pas. Puis j'ai pu la modifier.
Remarque au passage : comment se fait-il que ce candidat était enregistré sans adresse mail étant donné que ce champ est obligatoire ?

Info supplémentaire : Le champ email a été rendu obligatoire, donc il n'y a plus de cas d'emails vides à renseigner après coup. D'autre part, le champ email est modifiable après coup (testé).
