### ISSUE TITLE
Titre 1 moche quand actu promue en page d'accueil

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#68]
Créer une actu. Mettre la première phrase en style Titre 1. 
Promouvoir l'actu en page d'accueil. 
La première phrase apparait et toujours en Titre 1 --> c'est moche (Cf recette)

**Comment by yvandouenel** [comment]
En fait, il ne faut pas utiliser les titres de niveau 1 et 2 pour des raisons d'accessibilité et de référencement. Je les ai donc enlevé de l'éditeur de html (ckeditor).

**Comment by SandMat** [comment]
Le pb subsiste avec Titre 3 (ou en dessous). --> en page d'accueil, faire apparaitre la phrase en texte normal (pas de gras, pas de majuscules au milieu des mots). Garder les titres 3 et en-dessous quand on ouvre l'actu.
