### ISSUE TITLE
Je n'ai plus le menu "inscriptions aux réunions d'infos"

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#69]
Connectée en tant que Sandrine Mathon ou Cathy Beydon (sous-menu de Contenu)

**Comment by jabberwooki** [comment]
Effectivement, ce menu n'est plus visible que par le superadministrateur.
Pour des raisons obscures, impossible de le faire ré-apparaitre pour les rôles autorisés (webmaster, pôle gestion, référent). Donc sorti du menu Contenu et placé au premier niveau du menu d'administration, complètement à droite.
