### ISSUE TITLE
Pb avec les champs additionnels statuts en réunion d'infos

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#73]
Quand on modifie une inscription, les champs additionnels (n° RSA...) apparaissent groupés en-dessous des cases à cocher, et plus au niveau des cases concernées. 
Tester si les modifs de ces champs sont bien prises en compte.

**Comment by jabberwooki** [comment]
Corrigé.
Les champs additionnels sont repositionnés sous leur case à cocher dans le formulaire de modification comme dans le formulaire de création d'une inscription.
Les modifications de ces champs sont prises en compte.

D'autre part, le repositionnement des infos additionnelles a été fait aussi dans la fiche détaillée d'une inscription, fiche dans laquelles ces données étaient là aussi placées après les statuts, donc peu aisées à lire.
