### ISSUE TITLE
Publication intempestive d'une fiche référent

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#8]
En tant que référent, créer une fiche de marque. Enregsitrer comme brouillon 
--> la fiche est publiée automatiquement

Il y avait certes une demande qu'il n'y ait pas besoin de mail de validation avant publication si l'auteur de la fiche est référent. Mais tant que la fiche est sauvegardée en brouillon, elle ne doit pas être publiée. C'est seulement quand la version est considérée comme définitive qu'elle est publiée.

**Comment by SandMat** [comment]
Ce n'est pas une amélioration, c'est un bug (=comportement qui ne correspond pas aux attentes). Sauvegarde brouillon => brouillon. C'est juste l'étape de publication qui n'est pas nécessaire. Donc Sauvegarde définitive => publication, au lieu de passer par une validation référent.

**Comment by jabberwooki** [comment]
Bug non reproductible. Les tests effectués sont les suivants.
1) En local, sur mon site de dev :
- connexion en tant que "Sandrine Mathon".
- création d'une marque test, validation de la fiche marque en tant que brouillon
- modification de la marque nouvellement créée, le statut est "non publié".
- elle n'est pas visible dans l'écran de recherche des marques.

2) Sur le site de recette :
- connexion en tant que "Benoit Le Vacon".
- création d'une marque "Marque Test", validation de la fiche marque en tant que brouillon
- modification de la marque nouvellement créée, le statut est "non publié".
- elle n'est pas visible dans l'écran de recherche des marques. Je l'ai laissé, pour éventuels tests supplémentaires.
