### ISSUE TITLE
Comment modifie-t-on la taille de la fonte dans les éditeurs de texte? 

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#83]
Cf le titre de l'issue

**Comment by jabberwooki** [comment]
En utilisant le menu déroulant Taille dans la barre d'outils.
J'ai testé en me connectant sous ton compte.

![taille-police](https://cloud.githubusercontent.com/assets/1741337/15821784/3f01cfc6-2bf2-11e6-9fc7-ee2f0c329c42.jpg)
