### ISSUE TITLE
Menu "trouver un prestataire ou un artisan" n'est plus cliquable

### ISSUE THREAD

**Issue by Andrea34** [jabberwooki/crealead#85]
Lorsque l'on clique sur "trouver un prestataire ou un artisan" la redirection vers l'annuaire des co-entrepreneurs ne se fait plus.

**Comment by yvandouenel** [comment]
Merci de t'en être aperçue... C'est corrigé mais il faudra m'avertir quand vous voudrez activer une marque sectorielle car le menu ne peut plus être affiché sans mon intervention...
