### ISSUE TITLE
Le nom des marques et les titres des réalisations pas affichés dans les marques sectorielles

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#89]
Aller dans une page de marque sectorielle. 
Aller dans la partie "Marques". Le nom des marques ne s'affiche pas (il y a juste le logo et l'accroche).

Idem dans la partie Réalisation (du coup, quand il n'y a pas de photo et pas de résumé, ça fait juste un beau rectangle blanc. Cf Crealead Evolution).

**Comment by jabberwooki** [comment]
Pour les marques, comme pour les réalisations, l'info est bien présente dans le code de la page (nom de la marque, titre de la réalisation). Mais il y a un paramétrage custom fait par Yvan du côté intégration graphique. Le problème est à régler de ce côté-là.
Je lui transmets le ticket.
