### ISSUE TITLE
J'ai l'impression que la recherche par mot-clef ne cherche pas dans les mots-clefs des marques

### ISSUE THREAD

**Issue by SandMat** [jabberwooki/crealead#94]
Ex : chercher sur Alzheimer. 
Devrait retourner Pro Formations, qui a mis "accompagner Alzheimer" en mot-clef. 
Mais ça ne marche pas.

**Comment by jabberwooki** [comment]
Je viens de faire le test à l'instant sur la prod.
La recherche du mot-clé "Alzheimer" me retourne deux marques, Oxgène formation et Pro formation.
Et une autre recherche avec "accompagner Alzheimer" retourne Pro Formations seulement.
