### ISSUE TITLE
V3 S4-5 Agenda des salles à finaliser

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/crealead#99]
[Carte Trello](https://trello.com/c/MW54UnGc/351-4-5-agenda-des-salles-%C3%A0-finaliser)

J'ai traité les critères 1 (css) et 3 (dev).
Restent à faire les critères 2 (boutons Prec/Suiv) et 4 (amélioration menu Salles).

**Comment by yvandouenel** [comment]
C'est fait
